// <auto-generated />
namespace Inventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class supplier_and_customer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supplier_and_customer));
        
        string IMigrationMetadata.Id
        {
            get { return "202307210835293_supplier_and_customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
